# ========== Profile ========== #
# avatar
avatar: /avatar/avatar.jpg
# author name
author: 兰溪 
# signature
signature: 君子和而不同 
# SNS
social:
  email: 743703241@qq.com
  github: //github.com/EmbolismSoil
  # wechat and qq should be a path of qr-code image
  wechat:
  qq: 
  weibo: 
  zhihu: https://www.zhihu.com/people/li-brooks/activities
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  v2ex: 
  bilibili: 
  linkedin: 
  others: 
  rss: 
# friends
friends:
about:
  enable: true
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site
SEO_title: 兰溪
# main title
main_title: 兰溪
# subtitle
subtitle: 君子和而不同
# site haeder image
site_header_image: '/intro/bg-3.jpg'
# post haeder image
post_header_image: '/intro/bg-1.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 

# ========== Analytics ========== #
# Busuanzi pv analytics
busuanzi: true
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
